source 'https://rubygems.org' 

gem 'wohnung_mongodb', path: '../wohnung_mongodb'
gem 'wohnung', path: '../wohnung'

# sinatra
gem 'sinatra'
gem 'sinatra-contrib'

gem 'bson_ext', '1.5.2'
# the newer version of bson_ext throws an eror "undefined method `last' for nil:NilClass" when calling map_reduce
# https://groups.google.com/forum/#!msg/mongomapper/V6SxD8zUhz4/yXPpzLkV0nMJ

gem 'byebug'
gem 'debugger'